In [1]:
import json
import pandas as pd
import os

In [2]:
def extract_values(data, target_names):
    extracted_values = {}

    def traverse(obj):
        if isinstance(obj, dict):
            if 'name' in obj and obj['name'] in target_names and 'values' in obj:
                extracted_values[obj['name']] = obj['values']
            for key, value in obj.items():
                traverse(value)
        elif isinstance(obj, list):
            for item in obj:
                traverse(item)

    traverse(data)
    return extracted_values

# Function to extract only the 'values' from nested objects in specific columns
def clean_src_context_nested_values(dataframe):
    dataframe['src_context'] = dataframe['src_context'].apply(
        lambda x: x['values'] if isinstance(x, dict) and 'values' in x else x
    )
    return dataframe



# Function to extract only the 'values' field from lists of dictionaries
def extract_nested_values(column_data):
    values = column_data['values']
    print(values)
    new_values = []
    for val in values:
        new_values.extend(val['values'])
    return new_values

In [3]:
# Function to process a single JSON file
def process_json_file(file_path, target_names):
    with open(file_path, "r", encoding="utf-8") as file:
        json_data = json.load(file)

    # Extract values
    extracted_data = extract_values(json_data, target_names)

    # Convert the extracted data into a structured column-wise format
    max_length = max(len(v) for v in extracted_data.values()) if extracted_data else 0

    # Ensure all columns have the same number of rows by padding with None
    for key in extracted_data:
        while len(extracted_data[key]) < max_length:
            extracted_data[key].append(None)

    # Convert to DataFrame
    df_structured = pd.DataFrame(extracted_data)

    # Function to extract only the 'values' from nested objects in specific columns
    df_structured = clean_src_context_nested_values(df_structured)
    # Apply the function to the 'tgt_contexts' column
    if 'tgt_contexts' in df_structured.columns:
        df_structured['tgt_contexts'] = df_structured['tgt_contexts'].apply(extract_nested_values)


    return df_structured

In [4]:
# Function to process all JSON files in a directory
def process_all_json_in_directory(directory_path, target_names, output_csv_path):
    all_dataframes = []
    
    for filename in os.listdir(directory_path):
        if filename.endswith(".json"):
            file_path = os.path.join(directory_path, filename)
            print(f"Processing: {file_path}")
            df = process_json_file(file_path, target_names)
            df["source_file"] = filename  # Add a column to track the source file
            all_dataframes.append(df)

    # Combine all DataFrames
    final_df = pd.concat(all_dataframes, ignore_index=True)

    # Save to CSV
    final_df.to_csv(output_csv_path, index=False, encoding="utf-8-sig")

    print(f"Saved combined DataFrame to {output_csv_path}")

In [5]:
# Target names to extract values from
# Directory containing JSON files
json_directory = "/Users/anniewang/Desktop/infogap/scratch/ethics_annotation_save"  # Change this to your directory path
output_csv = "combined_data.csv"
target_names = {'fact', 'src_context', 'person_name', 'tgt_contexts', 'gpt-4o_intersection_label', 'sam_annotations'}

# Process all JSON files in the directory and save the combined CSV
process_all_json_in_directory(json_directory, target_names, output_csv)

Processing: /Users/anniewang/Desktop/infogap/scratch/ethics_annotation_save/annotation_20f_2025-02-18_Dosa (food).json
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['প্রকারভেদে দোসা তৈরির একধিক পদ্ধতি আছে।', 'এখানে সাধারণ একটি পদ্ধতি বর্ণনা করা হলো।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ["গাঁজন প্রক্রিয়া ভিটামিন বি এবং সি'র পরিমাণ বাড়িয়ে দেয়।", 'প্রকারভেদে দোসা তৈরির একধিক পদ্ধতি আছে।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The batter is ladled onto a hot tava or griddle greased with oil or ghee.', 'The batter is spread out with the base of a ladle or a bowl to form a pancake.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The batter is mixed with water to get the desired consistency.', 'The batter is ladled onto a hot tava or griddle greased with oil or ghee.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['After adding salt, the batter is allowed to ferment overnight.', 'The batter is mixed with water to get the desired consistency.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The fermentation process of dosa increases the vitamin C content.', 'A mixture of rice and white gram that has been soaked in water for at least 4–5 hours is ground finely to form a batter.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['একইভাবে বাকি দোসাগুলোও বানিয়ে নিতে হবে', 'দোসার সাথে বিভিন্ন সবজি এবং সস দিয়ে খাওয়া হয়।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['অঞ্চল ও ব্যক্তিভেদে দোসাতে ব্যবহৃত সবজি তরকারির ধরন আলাদা হয়।', 'সাধারণত সাম্বার, ভেজা চাটনি, শুকনা চাটনি, ভারতীয় আচার ইত্যাদি দিয়ে দোসা পরিবেশন করা হয়।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Indian pickles are a variety of pickles originating from the Indian subcontinent.', 'They are made from various fruits and vegetables.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The mixture of white grams and rice can be replaced with highly refined wheat flour or semolina.', 'Dosas can be stuffed with fillings of vegetables and sauces to make a quick meal.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': 'SORTED_ASC', 'values': ['ধোসা হচ্ছে ভারতীয় উপমহাদেশের একটি রুটিজাতীয় খাবার।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['প্রথাগতভাবে গরম সাম্বার, আলু তরকারি, পনির বা চাটনির সঙ্গে ধোসা পরিবেশন করা হয়।', 'বাংলাদেশের কিছু অঞ্চলে ধোসা চাপটি, চাপড়া পিঠা, চটা পিঠা নামে পরিচিত।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['ধোসা আটার গোলা বা খামি থেকে তৈরী করা হয়।', 'ধোসার প্রধান উপাদান চাল এবং কলাইয়ের ডাল।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['কোন চিনি বা সম্পৃক্ত চর্বি থাকেনা।', 'যেহেতু এর প্রধান উপাদান চাল এবং কলাইয়ের ডাল তাই এতে প্রচুর পরিমাণে প্রোটিন থাকে।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The introduction of dosa abroad was due to the migration of the Indian Tamil diaspora to Southeast Asia.', 'The introduction of dosa abroad was due to the migration of the Indian Tamil diaspora to the Western World.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Dosa was introduced far abroad since the early 18th century.', 'The introduction of dosa abroad was due to the migration of the Indian Tamil diaspora to Southeast Asia.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['After adding salt, the batter is allowed to ferment overnight.', 'The batter is mixed with water to get the desired consistency.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The fermentation process of dosa increases the vitamin C content.', 'A mixture of rice and white gram that has been soaked in water for at least 4–5 hours is ground finely to form a batter.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['বাংলাদেশের কিছু অঞ্চলে ধোসা চাপটি, চাপড়া পিঠা, চটা পিঠা নামে পরিচিত।', 'দোসায় উচ্চমাত্রায় শর্করা থাকে।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['যেহেতু এর প্রধান উপাদান চাল এবং কলাইয়ের ডাল তাই এতে প্রচুর পরিমাণে প্রোটিন থাকে।', "গাঁজন প্রক্রিয়া ভিটামিন বি এবং সি'র পরিমাণ বাড়িয়ে দেয়।"]}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['দোসায় উচ্চমাত্রায় শর্করা থাকে।', 'কোন চিনি বা সম্পৃক্ত চর্বি থাকেনা।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['বাংলাদেশের কিছু অঞ্চলে ধোসা চাপটি, চাপড়া পিঠা, চটা পিঠা নামে পরিচিত।', 'দোসায় উচ্চমাত্রায় শর্করা থাকে।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['ধোসা হচ্ছে ভারতীয় উপমহাদেশের একটি রুটিজাতীয় খাবার।', 'ধোসা আটার গোলা বা খামি থেকে তৈরী করা হয়।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': 'SORTED_ASC', 'values': ['ধোসা হচ্ছে ভারতীয় উপমহাদেশের একটি রুটিজাতীয় খাবার।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['A dosa is made from a fermented batter of ground black gram and rice.', 'Dosas are served hot.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The proportion of rice to lentils is generally 3:1 or 4:1.', 'After adding salt, the batter is allowed to ferment overnight.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['একইভাবে বাকি দোসাগুলোও বানিয়ে নিতে হবে', 'দোসার সাথে বিভিন্ন সবজি এবং সস দিয়ে খাওয়া হয়।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['দোসার সাথে বিভিন্ন সবজি এবং সস দিয়ে খাওয়া হয়।', 'অঞ্চল ও ব্যক্তিভেদে দোসাতে ব্যবহৃত সবজি তরকারির ধরন আলাদা হয়।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['After adding salt, the batter is allowed to ferment overnight.', 'The batter is mixed with water to get the desired consistency.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The proportion of rice to lentils is generally 3:1 or 4:1.', 'After adding salt, the batter is allowed to ferment overnight.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': 'SORTED_ASC', 'values': ['ধোসা হচ্ছে ভারতীয় উপমহাদেশের একটি রুটিজাতীয় খাবার।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['ধোসার প্রধান উপাদান চাল এবং কলাইয়ের ডাল।', 'ধোসা দক্ষিণ ভারতীয়দের খাদ্যাভ্যাসে গুরুত্বপূর্ণ স্থান দখল করে আছে।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['ধোসার প্রধান উপাদান চাল এবং কলাইয়ের ডাল।', 'ধোসা দক্ষিণ ভারতীয়দের খাদ্যাভ্যাসে গুরুত্বপূর্ণ স্থান দখল করে আছে।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['ধোসা দক্ষিণ ভারতীয়দের খাদ্যাভ্যাসে গুরুত্বপূর্ণ স্থান দখল করে আছে।', 'ধোসা বাংলাদেশ, ভারত, পাকিস্তান সহ ভারতীয় উপমহাদেশে জনপ্রিয়।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The introduction of dosa abroad was due to the migration of the Indian Tamil diaspora to Southeast Asia.', 'The introduction of dosa abroad was due to the migration of the Indian Tamil diaspora to the Western World.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Dosa was introduced far abroad since the early 18th century.', 'The introduction of dosa abroad was due to the migration of the Indian Tamil diaspora to Southeast Asia.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['একইভাবে বাকি দোসাগুলোও বানিয়ে নিতে হবে', 'দোসার সাথে বিভিন্ন সবজি এবং সস দিয়ে খাওয়া হয়।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': 'SORTED_ASC', 'values': ['ধোসা হচ্ছে ভারতীয় উপমহাদেশের একটি রুটিজাতীয় খাবার।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': 'SORTED_ASC', 'values': ['ধোসা হচ্ছে ভারতীয় উপমহাদেশের একটি রুটিজাতীয় খাবার।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['ধোসার প্রধান উপাদান চাল এবং কলাইয়ের ডাল।', 'ধোসা দক্ষিণ ভারতীয়দের খাদ্যাভ্যাসে গুরুত্বপূর্ণ স্থান দখল করে আছে।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Dosa is typically made with lentils.', 'Other versions of dosa exist.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Pancakes are popular in many countries around the world.', 'Different cultures have their own variations of pancakes.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['After adding salt, the batter is allowed to ferment overnight.', 'The batter is mixed with water to get the desired consistency.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The fermentation process of dosa increases the vitamin C content.', 'A mixture of rice and white gram that has been soaked in water for at least 4–5 hours is ground finely to form a batter.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': 'SORTED_ASC', 'values': ['ধোসা হচ্ছে ভারতীয় উপমহাদেশের একটি রুটিজাতীয় খাবার।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['ধোসার প্রধান উপাদান চাল এবং কলাইয়ের ডাল।', 'ধোসা দক্ষিণ ভারতীয়দের খাদ্যাভ্যাসে গুরুত্বপূর্ণ স্থান দখল করে আছে।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Idli podi can also be mixed with groundnut oil.', 'Idli podi can also be mixed with ghee.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Some add a bit of soaked fenugreek seeds while grinding the batter.', 'The proportion of rice to lentils is generally 3:1 or 4:1.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['ধোসা হচ্ছে ভারতীয় উপমহাদেশের একটি রুটিজাতীয় খাবার।', 'ধোসা আটার গোলা বা খামি থেকে তৈরী করা হয়।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['ধোসা বাংলাদেশ, ভারত, পাকিস্তান সহ ভারতীয় উপমহাদেশে জনপ্রিয়।', 'প্রথাগতভাবে গরম সাম্বার, আলু তরকারি, পনির বা চাটনির সঙ্গে ধোসা পরিবেশন করা হয়।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['একইভাবে বাকি দোসাগুলোও বানিয়ে নিতে হবে', 'দোসার সাথে বিভিন্ন সবজি এবং সস দিয়ে খাওয়া হয়।']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['দোসার সাথে বিভিন্ন সবজি এবং সস দিয়ে খাওয়া হয়।', 'অঞ্চল ও ব্যক্তিভেদে দোসাতে ব্যবহৃত সবজি তরকারির ধরন আলাদা হয়।']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Dosa is a good source of protein.', 'A typical homemade plain dosa without oil contains about 112 calories.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The dosa earned the Guinness World Record for the longest dosa.', 'In a November 2019 video, United States Vice President Kamala Harris promoted her campaign for presidency.']}]
Processing: /Users/anniewang/Desktop/infogap/scratch/ethics_annotation_save/annotation_20f_2025-02-05_乌龙茶.json
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Some of the better known cliff teas are:', 'Dancong tea refers to a family of strip-style oolong teas from Guangdong Province.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Oolong tea is made from the Camellia sinensis plant.', "The name 'oolong' means 'black dragon' tea."]}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Oolong contains caffeine.', 'The caffeine content in tea will vary based on terroir.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Several types of oolong tea, including those produced in the Wuyi Mountains, Nanping of northern Fujian, such as Da Hong Pao, are among the most famous Chinese teas.', 'Different varieties of oolong are processed differently.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['1866年台湾乌龙茶开始外销。', '现在全中国大陆乌龙茶最大产地是福建安溪。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['乌龙茶创制于1725年（清雍正年间）前后。', '福建《安溪县志》记载，安溪人于清雍正三年首先发明乌龙茶做法。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Some of the better known cliff teas are:', 'Dancong tea refers to a family of strip-style oolong teas from Guangdong Province.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Oolong (UK:/ˈuːlɒŋ/, US:/-lɔːŋ/) is a traditional semi-oxidized Chinese tea.', 'Oolong tea is made from the Camellia sinensis plant.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Some of the better known cliff teas are:', 'Dancong tea refers to a family of strip-style oolong teas from Guangdong Province.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Oolong (UK:/ˈuːlɒŋ/, US:/-lɔːŋ/) is a traditional semi-oxidized Chinese tea.', 'Oolong tea is made from the Camellia sinensis plant.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['现在全中国大陆乌龙茶最大产地是福建安溪。', '安溪于1995年被中国国家农业部和中国农学会等单位命名为“中国乌龙茶（名茶）之乡”。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['乌龙茶做法后来传入闽北和台湾。', '据史料考证，1862年福州即设有经营乌龙茶的茶栈。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['烏龍茶既有绿茶的清新，又有红茶的甜醇。', '在中國大陸，烏龍茶等同於青茶。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['烏龍茶的分類和作法視地域而有所不同。', '在中國大陸，烏龍茶的茶葉加工分類上屬於綠紅黃白黑青六大茶系中的青茶。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['乌龙茶创制于1725年（清雍正年间）前后。', '福建《安溪县志》记载，安溪人于清雍正三年首先发明乌龙茶做法。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['现在的乌龙茶是安溪人仿照武夷山茶的制法，改进工艺制作出来的一种茶。', '乌龙茶创制于1725年（清雍正年间）前后。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['现在全中国大陆乌龙茶最大产地是福建安溪。', '安溪于1995年被中国国家农业部和中国农学会等单位命名为“中国乌龙茶（名茶）之乡”。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['现在的乌龙茶是安溪人仿照武夷山茶的制法，改进工艺制作出来的一种茶。', '乌龙茶创制于1725年（清雍正年间）前后。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Teas with a unique, sweet taste from higher elevations in Taiwan fetch a premium price.', 'Recommended brewing techniques for oolong tea vary widely.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The Fujian preparation process known as the gongfu tea ceremony is associated with oolong tea.', 'Different styles of oolong tea can vary widely in flavor.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Some of the better known cliff teas are:', 'Dancong tea refers to a family of strip-style oolong teas from Guangdong Province.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Oolong tea is also popular among ethnic Chinese in Southeast Asia.', 'The Fujian preparation process known as the gongfu tea ceremony is associated with oolong tea.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['现在全中国大陆乌龙茶最大产地是福建安溪。', '安溪于1995年被中国国家农业部和中国农学会等单位命名为“中国乌龙茶（名茶）之乡”。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['乌龙茶的名字大致有四种来源可能。', '第一种来源可能是产地说。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The flavor of oolong tea depends on the horticulture and style of production.', 'Several types of oolong tea, including those produced in the Wuyi Mountains, Nanping of northern Fujian, such as Da Hong Pao, are among the most famous Chinese teas.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Some of the better known cliff teas are:', 'Dancong tea refers to a family of strip-style oolong teas from Guangdong Province.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Much more attention to timing and temperature is necessary in the manufacturing of oolong tea compared to black tea.', 'There are three widely espoused explanations of the origin of the name of Oolong tea.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['There are three widely espoused explanations of the origin of the name of Oolong tea.', "According to the 'tribute tea' theory, oolong tea came directly from Dragon-Phoenix Tea Cake tribute tea."]}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Oolong contains caffeine.', 'The caffeine content in tea will vary based on terroir.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Several types of oolong tea, including those produced in the Wuyi Mountains, Nanping of northern Fujian, such as Da Hong Pao, are among the most famous Chinese teas.', 'Different varieties of oolong are processed differently.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['在中國大陸，烏龍茶的茶葉加工分類上屬於綠紅黃白黑青六大茶系中的青茶。', '烏龍茶是經過部份发酵的茶。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['烏龍茶的製茶方法十分多元化。', '烏龍茶除灌木外，甚至有部份使用小喬木種。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['True dancongs are not common outside China.', 'Tea cultivation in Taiwan began in the 18th century.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ["The Chinese term 'wulong' (oolong) was first used to describe a tea in the 1857 text 'Miscellaneous Notes on Fujian' by Shi Hongbao.", "In Taiwan, oolong teas are also known as 'qingcha' (Chinese: 青茶; pinyin: qīngchá; Pe̍h-ōe-jī: chheⁿ-tê) or 'dark green teas' since early 2000."]}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['烏龍茶的分類和作法視地域而有所不同。', '在中國大陸，烏龍茶的茶葉加工分類上屬於綠紅黃白黑青六大茶系中的青茶。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['烏龍茶既有绿茶的清新，又有红茶的甜醇。', '在中國大陸，烏龍茶等同於青茶。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['北苑茶在唐末已产茶。', '宋朝及其后，北苑茶的产量扩大。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['现在全中国大陆乌龙茶最大产地是福建安溪。', '安溪于1995年被中国国家农业部和中国农学会等单位命名为“中国乌龙茶（名茶）之乡”。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['乌龙茶的名字来源有很多传说。', '乌龙茶的名字大致有四种来源可能。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['台灣烏龍茶是專指以烏龍茶方式加工的茶種。', '乌龙茶的名字来源有很多传说。']}]
Processing: /Users/anniewang/Desktop/infogap/scratch/ethics_annotation_save/annotation_2025-02-17_Sundae (sausage).json
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Eogyo-sundae (어교순대) is made with the swim bladder of brown croakers.', 'In South Korea, sundae is often steamed and served with steamed offals such as gan (liver) and heopa (lung).']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Sliced pieces of sundae and sides are dipped in vinegar-gochujang mixture in Honam.', 'Sliced pieces of sundae and sides are dipped in seasoned soybean paste in Yeongnam.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['It might offer cooking tips.', 'It can have articles on food trends.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['It can have articles on food trends.', 'It may include videos related to food.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Other fillings for sundae include kkaennip (perilla leaves), scallions, doenjang (soybean paste), kimchi, and soybean sprouts.', 'Abai-sundae (아바이순대) is from the Hamgyong and Pyongan Provinces.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['It also contains pork fat or beef suet.', 'Oatmeal, oat groats, or barley groats are used as fillers.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['현재 당면순대의 90% 가량은 공장에서 제조되고 있다.', '당면순대는 대표적인 분식 메뉴이기도 하다.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': 'SORTED_ASC', 'values': ['순대는 한국의 음식이다.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['It might offer cooking tips.', 'It can have articles on food trends.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['It can have articles on food trends.', 'It may include videos related to food.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['It is a key component of Burns Night suppers.', 'Burns Night is celebrated on January 25th in honor of the poet Robert Burns.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Burns Night is celebrated on January 25th in honor of the poet Robert Burns.', 'Kaszanka is a traditional Polish blood sausage.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['용궁순대는 경상북도 예천군 용궁면 일대의 순대이다.', '용궁순대는 돼지의 막창으로 만든다.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['만든 지역에 따라 병천 순대, 아바이 순대 등이 있다.', '충청도는 대게 새우젓과 먹는다.']}]

In [43]:

# Extract values
extracted_data = extract_values(json_data, target_names)

# Convert the extracted data into a structured column-wise format
max_length = max(len(v) for v in extracted_data.values()) if extracted_data else 0

# Ensure all columns have the same number of rows by padding with None
for key in extracted_data:
    while len(extracted_data[key]) < max_length:
        extracted_data[key].append(None)

# Convert to DataFrame
df_structured = pd.DataFrame(extracted_data)

df_structured

,fact,person_name,src_context,tgt_contexts,gpt-4o_intersection_label,sam_annotations
0,加上卫生的考虑，现代月饼通常都会用透明塑胶袋作独立包装。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",yes,A
1,回收月饼是为了避免市场上出现陈馅月饼，保证品牌品質。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
2,"The ingredients usually consist of: jam, dried...",Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,A
3,此说并未有文献核实。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
4,有關月餅的典故有多個說法。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
5,Mooncakes have a central role in the Mid-Autum...,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,D
6,加上卫生的考虑，现代月饼通常都会用透明塑胶袋作独立包装。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",yes,A
7,Traditional mooncakes are circular like a moon...,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
8,《洛中見聞》記載唐朝中秋節新科進士曲江宴時，唐僖宗命御膳房用紅綾將餅賞賜給進士。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
9,Mooncakes are very popular as gifts to clients...,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
10,Many hotels and fine Chinese cuisine restauran...,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
11,Vietnamese mooncakes have two basic parts: cru...,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",yes,E
12,已经解冻的冰皮月饼不应反复冷藏。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
13,在进食前约两小时，可把冰皮月饼移到4摄氏度的冰箱（例如双门冰箱的下层），令月饼略为软化以便切开。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
14,Mooncakes are also found in stalls of large su...,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E
15,Vietnamese mooncakes are usually sold either i...,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",yes,D
16,各類台式月餅如蛋黃酥和綠豆椪即使在非中秋時節仍可能買得到。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",yes,B
17,Another method of hiding a message was to prin...,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,D
18,Mooncakes have a central role in the Mid-Autum...,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,B
19,《洛中見聞》記載唐朝中秋節新科進士曲江宴時，唐僖宗命御膳房用紅綾將餅賞賜給進士。,Mooncae,"{'name': '', 'datatype': 'Utf8', 'bit_settings...","{'name': '', 'datatype': {'List': 'Utf8'}, 'bi...",no,E

In [44]:
df_structured['tgt_contexts'].iloc[0]

{'name': '',
 'datatype': {'List': 'Utf8'},
 'bit_settings': '',
 'values': [{'name': '',
   'datatype': 'Utf8',
   'bit_settings': '',
   'values': ['Customers can pick and choose the filling of mooncakes that suits their taste and diet.',
    'For added hygiene, each mooncake is often wrapped in airtight plastic.']},
  {'name': '',
   'datatype': 'Utf8',
   'bit_settings': '',
   'values': ['For added hygiene, each mooncake is often wrapped in airtight plastic.',
    'Each mooncake is often accompanied by a tiny food preserver packet.']}]}

In [49]:
# Function to extract only the 'values' from nested objects in specific columns
def clean_src_context_nested_values(dataframe):
    dataframe['src_context'] = dataframe['src_context'].apply(
        lambda x: x['values'] if isinstance(x, dict) and 'values' in x else x
    )
    return dataframe

# Clean the DataFrame
df_structured = clean_src_context_nested_values(df_structured)

# Function to extract only the 'values' field from lists of dictionaries
def extract_nested_values(column_data):
    values = column_data['values']
    print(values)
    new_values = []
    for val in values:
        new_values.extend(val['values'])
    return new_values

# Apply the function to the 'tgt_contexts' column
if 'tgt_contexts' in df_structured.columns:
    df_structured['tgt_contexts'] = df_structured['tgt_contexts'].apply(extract_nested_values)

[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Customers can pick and choose the filling of mooncakes that suits their taste and diet.', 'For added hygiene, each mooncake is often wrapped in airtight plastic.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['For added hygiene, each mooncake is often wrapped in airtight plastic.', 'Each mooncake is often accompanied by a tiny food preserver packet.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['It is customary for families to present mooncakes to their relatives as presents.', 'Presenting mooncakes as presents encourages the market for high-end mooncakes.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Over time, both the crusts and the composition of the fillings of mooncakes have diversified.', 'The diversification of mooncakes is due to a commercial need to drive up sales.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['传统月饼的皮因制酥法多种，有多样酥皮。', '传统月饼的馅因用枣泥、五仁、豆沙、松仁、火腿及香料。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['已经解冻的冰皮月饼不应反复冷藏。', '传统月饼的制法是以水油面团或酥油面团摘剂作皮。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['After malaxating rice flour, fillings similar to that of baked mooncake are stuffed inside the crust.', 'The cake is put into the mold dusted with a thin layer of flour to prevent sticking to fingers.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The cake can be used immediately without any further steps.', 'Bánh dẻo is not as popular as bánh nướng.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Three types of mooncake crust are used in Chinese cuisine.', 'There are many regional variants of the mooncake.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The salted egg yolks in mooncakes symbolize the full moon.', 'Mooncakes may be steamed.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['台式月餅就如一般糕餅一樣。', '月餅在中秋節有龐大商機。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['韓國有松片。', '古代月饼被作为祭品于中秋节所食。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Customers can pick and choose the filling of mooncakes that suits their taste and diet.', 'For added hygiene, each mooncake is often wrapped in airtight plastic.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['For added hygiene, each mooncake is often wrapped in airtight plastic.', 'Each mooncake is often accompanied by a tiny food preserver packet.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['传统月饼的制法是以水油面团或酥油面团摘剂作皮。', '传统月饼的内馅成扁圆形生胚。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['传统月饼的内馅成扁圆形生胚。', '传统月饼的生胚入模具压使表面呈凸凹花纹。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The festival is intricately linked to legends of Chang’e, the mythical Moon Goddess of Immortality.', 'According to the Liji, an ancient Chinese book recording customs and ceremonies, the Chinese Emperor should offer sacrifices to the Sun in spring and the Moon in autumn.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ["The Mid-Autumn festival is now commonly known as 'Mooncake Festival'.", 'There is a folk tale about the overthrow of the Yuan dynasty.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['無綫電視總經理曾志偉在三只羊網絡科技為該款「香港品牌」帶貨。', '消費者購得後發現「香港美誠月餅」並非在香港生產。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['月饼生产商还会尽量使用可循环再造的包装物料。', '近年来，中国大陆的部分公司会在每年中秋节定制本单位的月饼。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['近年来，中国大陆的部分公司会在每年中秋节定制本单位的月饼。', '近年来，中国大陆的部分大学会在每年中秋节定制本单位的月饼。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['月饼生产商还会尽量使用可循环再造的包装物料。', '近年来，中国大陆的部分公司会在每年中秋节定制本单位的月饼。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['已经解冻的冰皮月饼不应反复冷藏。', '传统月饼的制法是以水油面团或酥油面团摘剂作皮。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['铁罐印花也于60年代迄今取代了战前的纸盒包装。', '广式月饼的包装经常是四个为一单位。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Snowy mooncakes first appeared on the market in the early 1980s.', 'Snowy mooncakes are non-baked.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Snowy mooncakes are non-baked.', 'Snowy mooncakes are chilled.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Foreign food companies have also tried to cash in.', "Häagen-Dazs were one of the first to create an ice-cream mooncake, with a choice of either the 'traditional,' snow-skin, or Belgian/Swiss white, milk, and dark chocolate crusts."]}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Mooncakes containing taro paste and pineapple, which were considered novelty items at their time of invention, have become commonplace in recent years.', 'Filling composed of ingredients such as coffee, chocolate, nuts (walnuts, mixed nuts, etc.), fruits (prunes, pineapples, melons, lychees, etc.), vegetables (sweet potatoes, etc.), and even ham have been added to give a modern twist to the traditional recipes.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['消費者購得後發現「香港美誠月餅」並非在香港生產。', '在香港也沒有人知悉有該品牌的月餅。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['無綫電視總經理曾志偉在三只羊網絡科技為該款「香港品牌」帶貨。', '消費者購得後發現「香港美誠月餅」並非在香港生產。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['铁罐印花也于60年代迄今取代了战前的纸盒包装。', '广式月饼的包装经常是四个为一单位。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['冰皮月饼需要保持冷藏，以防止微生物大量滋生。', '大部分冰皮月饼都会使用塑料袋单独或两小个一起包装。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Traditional mooncakes are widely available all year long.', 'Regular modern mooncakes are usually only sold around the mid-autumn festival season.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['Bánh nướng and bánh dẻo are two special kinds of cake in Vietnam.', 'They are widely popular and are sold only during the Tết Trung Thu season.']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['传统月饼的内馅成扁圆形生胚。', '传统月饼的生胚入模具压使表面呈凸凹花纹。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['这些月饼通常采用特殊定制的外包装。', '这些月饼的外皮花纹会使用和单位相关的图案。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['台式月餅就如一般糕餅一樣。', '月餅在中秋節有龐大商機。']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['韓國有松片。', '古代月饼被作为祭品于中秋节所食。']}]
[{'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ['The festival is intricately linked to legends of Chang’e, the mythical Moon Goddess of Immortality.', 'According to the Liji, an ancient Chinese book recording customs and ceremonies, the Chinese Emperor should offer sacrifices to the Sun in spring and the Moon in autumn.']}, {'name': '', 'datatype': 'Utf8', 'bit_settings': '', 'values': ["The Mid-Autumn festival is now commonly known as 'Mooncake Festival'.", 'There is a folk tale about the overthrow of the Yuan dynasty.']}]

In [50]:
df_structured['tgt_contexts'].iloc[0]

['Customers can pick and choose the filling of mooncakes that suits their taste and diet.',
 'For added hygiene, each mooncake is often wrapped in airtight plastic.',
 'For added hygiene, each mooncake is often wrapped in airtight plastic.',
 'Each mooncake is often accompanied by a tiny food preserver packet.']

In [51]:
df_structured

,fact,person_name,src_context,tgt_contexts,gpt-4o_intersection_label,sam_annotations
0,加上卫生的考虑，现代月饼通常都会用透明塑胶袋作独立包装。,Mooncae,"[月饼在古时一般只以布包裹。, 使用月饼罐或纸盒包装是到了20世纪由于月饼被商品化才出现。,...",[Customers can pick and choose the filling of ...,yes,A
1,回收月饼是为了避免市场上出现陈馅月饼，保证品牌品質。,Mooncae,"[月饼的保质期最长不过30天。, 中秋过后许多大厂家都会回收月饼进行销毁。, 回收月饼是为了...",[It is customary for families to present moonc...,no,E
2,"The ingredients usually consist of: jam, dried...",Mooncae,"[Some other images, such as the sow with cub, ...","[传统月饼的皮因制酥法多种，有多样酥皮。, 传统月饼的馅因用枣泥、五仁、豆沙、松仁、火腿及香...",no,A
3,此说并未有文献核实。,Mooncae,"[『宫饼』在宫廷内流行，但也流传到民间。, 当时俗称『小饼』和『月团』。, 此说并未有文献核实。]","[After malaxating rice flour, fillings similar...",no,E
4,有關月餅的典故有多個說法。,Mooncae,"[可见月饼于当时流行于民间。, 清代已有详细记述月饼制作方法的书籍。如晚清女作家、女醫師曾懿...",[Three types of mooncake crust are used in Chi...,no,E
5,Mooncakes have a central role in the Mid-Autum...,Mooncae,[The 15th day of the 8th lunar month is the da...,"[台式月餅就如一般糕餅一樣。, 月餅在中秋節有龐大商機。, 韓國有松片。, 古代月饼被作为祭...",no,D
6,加上卫生的考虑，现代月饼通常都会用透明塑胶袋作独立包装。,Mooncae,"[月饼在古时一般只以布包裹。, 使用月饼罐或纸盒包装是到了20世纪由于月饼被商品化才出现。,...",[Customers can pick and choose the filling of ...,yes,A
7,Traditional mooncakes are circular like a moon...,Mooncae,"[In Indonesia, there are several main types of...","[传统月饼的制法是以水油面团或酥油面团摘剂作皮。, 传统月饼的内馅成扁圆形生胚。, 传统月饼...",no,E
8,《洛中見聞》記載唐朝中秋節新科進士曲江宴時，唐僖宗命御膳房用紅綾將餅賞賜給進士。,Mooncae,"[朱元璋奪取天下時適逢中秋佳節。, 朱元璋把當年起兵時以秘密傳遞訊息的月餅作為節令糕點賞賜群...",[The festival is intricately linked to legends...,no,E
9,Mooncakes are very popular as gifts to clients...,Mooncae,[Snowskin mooncakes in Singapore feature vario...,"[無綫電視總經理曾志偉在三只羊網絡科技為該款「香港品牌」帶貨。, 消費者購得後發現「香港美誠...",no,E
10,Many hotels and fine Chinese cuisine restauran...,Mooncae,[Mooncakes are very popular as gifts to client...,"[近年来，中国大陆的部分公司会在每年中秋节定制本单位的月饼。, 近年来，中国大陆的部分大学会...",no,E
11,Vietnamese mooncakes have two basic parts: cru...,Mooncae,[The designs of Vietnamese mooncakes largely r...,"[已经解冻的冰皮月饼不应反复冷藏。, 传统月饼的制法是以水油面团或酥油面团摘剂作皮。, 铁罐...",yes,E
12,已经解冻的冰皮月饼不应反复冷藏。,Mooncae,"[当冰皮月饼解冻后便要尽快食用。, 冰皮月饼在室温下摆放超过两小时后便应弃置。, 已经解冻的...",[Snowy mooncakes first appeared on the market ...,no,E
13,在进食前约两小时，可把冰皮月饼移到4摄氏度的冰箱（例如双门冰箱的下层），令月饼略为软化以便切开。,Mooncae,"[消费者在购买冰皮月饼后，应尽快放入零下18摄氏度的冰箱保存。, 消费者应只在进食前才开启冰...",[Foreign food companies have also tried to cas...,no,E
14,Mooncakes are also found in stalls of large su...,Mooncae,"[In Thailand, mooncakes (in Thai, ขนมไหว้พระจั...","[消費者購得後發現「香港美誠月餅」並非在香港生產。, 在香港也沒有人知悉有該品牌的月餅。, ...",no,E
15,Vietnamese mooncakes are usually sold either i...,Mooncae,[Mooncakes are also found in stalls of large s...,"[铁罐印花也于60年代迄今取代了战前的纸盒包装。, 广式月饼的包装经常是四个为一单位。, 冰...",yes,D
16,各類台式月餅如蛋黃酥和綠豆椪即使在非中秋時節仍可能買得到。,Mooncae,"[在台灣，月餅並不只在中秋時食用。, 外地傳入之月餅除外。, 各類台式月餅如蛋黃酥和綠豆椪即...",[Traditional mooncakes are widely available al...,yes,B
17,Another method of hiding a message was to prin...,Mooncae,"[The mooncakes contained a secret message., Th...","[传统月饼的内馅成扁圆形生胚。, 传统月饼的生胚入模具压使表面呈凸凹花纹。, 这些月饼通常采...",no,D
18,Mooncakes have a central role in the Mid-Autum...,Mooncae,[The 15th day of the 8th lunar month is the da...,"[台式月餅就如一般糕餅一樣。, 月餅在中秋節有龐大商機。, 韓國有松片。, 古代月饼被作为祭...",no,B
19,《洛中見聞》記載唐朝中秋節新科進士曲江宴時，唐僖宗命御膳房用紅綾將餅賞賜給進士。,Mooncae,"[朱元璋奪取天下時適逢中秋佳節。, 朱元璋把當年起兵時以秘密傳遞訊息的月餅作為節令糕點賞賜群...",[The festival is intricately linked to legends...,no,E